/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shreedharn' at '10/17/15 12:38 AM' with Gradle 2.6
 *
 * @author shreedharn, @date 10/17/15 12:38 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
